# Generated by Django 5.2.4 on 2025-07-20 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=200, verbose_name='Bot Token')),
                ('admin_id', models.BigIntegerField(verbose_name='Admin ID')),
                ('webhook_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Webhook URL')),
                ('webhook_path', models.CharField(default='/webhook', max_length=50, verbose_name='Webhook Path')),
                ('webapp_host', models.CharField(default='0.0.0.0', max_length=50, verbose_name='WebApp Host')),
                ('webapp_port', models.IntegerField(default=8080, verbose_name='WebApp Port')),
            ],
            options={
                'verbose_name': 'Bot sozlamalari',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Mashina nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mashina',
                'verbose_name_plural': 'Mashinalar',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Marshrut nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marshrut',
                'verbose_name_plural': 'Marshrutlar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=200, verbose_name="Yo'nalish")),
                ('date', models.DateField(verbose_name='Sana')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('trip_type', models.CharField(choices=[('person', 'Odam'), ('cargo', 'Pochta')], max_length=10, verbose_name='Sayohat turi')),
                ('car', models.CharField(max_length=100, verbose_name='Mashina')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='set_main.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
